In [1]:
import numpy as np
print(np.__version__)

2.4.2


- 데이터 분석: 수치형 변수와 요약, 통계,시각화
- 이미지 처리: 이미지데이터 표현하는 데 사용
- 게임/시뮬레이션: 구현을 위한 시뮬레이션 데이터 사용
- 머신러닝/딥러닝: 금융, 의료, 실험, 센서 데이터 사용

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))  # [1 2 3 4 5]
arr.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [19]:
np.array([10]).shape, np.array([10]).ndim

((1,), 1)

In [18]:
np.array(7).shape, np.array(7).ndim

((), 0)

In [20]:
np.array([[10,10], [15,15]]).shape, np.array([[10,10], [15,15]]).ndim

((2, 2), 2)

In [22]:
np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]]).shape, np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]]).ndim

((2, 2, 3), 3)

In [23]:
# 배열 생성
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 배열의 속성 확인
print('배열의 차원:', arr.ndim)         # 2
print('배열의 형태:', arr.shape)        # (3, 3)
print('배열의 크기:', arr.size)         # 9
print('배열의 데이터 타입:', arr.dtype) # int64
print('배열 요소의 크기:', arr.itemsize) # 8 (바이트)
print('배열의 strides:', arr.strides)   # (24, 8)

배열의 차원: 2
배열의 형태: (3, 3)
배열의 크기: 9
배열의 데이터 타입: int64
배열 요소의 크기: 8
배열의 strides: (24, 8)


In [25]:
# 리스트로부터 배열 생성
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

arr1.shape, arr12.shape

((5,), (2, 5))

In [45]:
# 리스트로부터 배열 생성
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

arr13=np.array([
  [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11,22, 33, 55, 44]
])
arr13.shape
arr13.dtype

dtype('int64')

In [34]:
np.arange(1, 16).reshape(3,5)
arr13.shape

(3, 5)

In [38]:
arr2 = np.zeros(5)
print(arr2)
arr2.shape

[0. 0. 0. 0. 0.]


(5,)

In [40]:
arr3 = np.ones((3, 3))
print(arr3)
arr3.shape

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


(3, 3)

In [42]:
# 1부터 10까지 2씩 증가
range_arr = np.arange(1, 10, 2)  
print(range_arr)
range_arr.shape


[1 3 5 7 9]


(5,)

In [44]:
 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)
linspace_arr.shape

[  0.  25.  50.  75. 100.]


(5,)

In [47]:
# 1. 데이터 샘플링
population = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
samples = np.random.choice(population, size=5, replace=False)
print("무작위 샘플:", samples)

# 2. 데이터 셔플링
data = np.arange(10)
np.random.shuffle(data)
print("셔플된 데이터:", data)

# 3. 확률 분포에 따른 데이터 생성
# 정규 분포 (평균=0, 표준편차=1)
normal_dist = np.random.normal(0, 1, 1000)

# 이항 분포 (n=10, p=0.5)
binomial_dist = np.random.binomial(n=10, p=0.5, size=1000)

# 포아송 분포 (lambda=2)
poisson_dist = np.random.poisson(lam=2, size=1000)

무작위 샘플: [7 1 3 4 8]
셔플된 데이터: [8 5 9 3 7 2 0 4 1 6]


In [46]:
# 다양한 데이터 타입의 배열 생성
#dtype 속성; np.int32 상수, ‘int32’ 문자열 형식으로 지정
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=np.bool_)

print("정수 배열의 dtype:", int_array.dtype)
print("실수 배열의 dtype:", float_array.dtype)
print("불리언 배열의 dtype:", bool_array.dtype)

정수 배열의 dtype: int32
실수 배열의 dtype: float64
불리언 배열의 dtype: bool


In [ ]:
# 데이터 타입 변환 예제, 소수점만 떨어진다.
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [49]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생

ValueError: invalid literal for int() with base 10: np.str_('three')

In [50]:
arr_str.dtype

dtype('<U5')

In [51]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [52]:
# 4x3x4x3 행렬 생성
arr_4d_example = np.arange(144).reshape(4, 3, 4, 3)
print(arr_4d_example.shape)  # (4, 3, 4, 3)
print(arr_4d_example)

(4, 3, 4, 3)
[[[[  0   1   2]
   [  3   4   5]
   [  6   7   8]
   [  9  10  11]]

  [[ 12  13  14]
   [ 15  16  17]
   [ 18  19  20]
   [ 21  22  23]]

  [[ 24  25  26]
   [ 27  28  29]
   [ 30  31  32]
   [ 33  34  35]]]


 [[[ 36  37  38]
   [ 39  40  41]
   [ 42  43  44]
   [ 45  46  47]]

  [[ 48  49  50]
   [ 51  52  53]
   [ 54  55  56]
   [ 57  58  59]]

  [[ 60  61  62]
   [ 63  64  65]
   [ 66  67  68]
   [ 69  70  71]]]


 [[[ 72  73  74]
   [ 75  76  77]
   [ 78  79  80]
   [ 81  82  83]]

  [[ 84  85  86]
   [ 87  88  89]
   [ 90  91  92]
   [ 93  94  95]]

  [[ 96  97  98]
   [ 99 100 101]
   [102 103 104]
   [105 106 107]]]


 [[[108 109 110]
   [111 112 113]
   [114 115 116]
   [117 118 119]]

  [[120 121 122]
   [123 124 125]
   [126 127 128]
   [129 130 131]]

  [[132 133 134]
   [135 136 137]
   [138 139 140]
   [141 142 143]]]]


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [56]:
# 3행 3열 리스트: [제품A(1,2,3일), 제품B(1,2,3일), 제품C(1,2,3일)]
production_data = [
    [100, 150, 120],  # 제품 A의 3일간 생산량
    [200, 180, 220],  # 제품 B의 3일간 생산량
    [90, 110, 100]    # 제품 C의 3일간 생산량
]

# 제품별 합계 계산
product_sums = [sum(product) for product in production_data]

# 제품 합계 출력
print("\n제품별 총 생산량:")
print(f"제품 A 합계: {product_sums[0]}")
print(f"제품 B 합계: {product_sums[1]}")
print(f"제품 C 합계: {product_sums[2]}")


제품별 총 생산량:
제품 A 합계: 370
제품 B 합계: 600
제품 C 합계: 300


In [61]:
prod_data=np.array(production_data)
prod_data.shape

(3, 3)

In [62]:
np.sum(prod_data, axis=1)

array([370, 600, 300])

In [64]:
np.sum(prod_data, axis=0)

array([390, 440, 440])

In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [65]:
# 기본 산술 연산 예제
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# 덧셈
print("덧셈:", arr1 + arr2)  # [6 8 10 12]

# 뺄셈
print("뺄셈:", arr2 - arr1)  # [4 4 4 4]

# 곱셈
print("곱셈:", arr1 * arr2)  # [5 12 21 32]

# 나눗셈
print("나눗셈:", arr2 / arr1)  # [5. 3. 2.33... 2.]

# 제곱
print("제곱:", np.square(arr1))  # [1 4 9 16]

# 제곱근
print("제곱근:", np.sqrt(arr1))  # [1. 1.41421356 1.73205081 2.]

# 지수
print("지수:", np.exp(arr1))  # [2.71828183 7.3890561 20.08553692 54.59815003]

# 로그
print("로그:", np.log(arr1))  # [0. 0.69314718 1.09861229 1.38629436]

덧셈: [ 6  8 10 12]
뺄셈: [4 4 4 4]
곱셈: [ 5 12 21 32]
나눗셈: [5.         3.         2.33333333 2.        ]
제곱: [ 1  4  9 16]
제곱근: [1.         1.41421356 1.73205081 2.        ]
지수: [ 2.71828183  7.3890561  20.08553692 54.59815003]
로그: [0.         0.69314718 1.09861229 1.38629436]


In [ ]:
# 생산량*단가(이익율)=총매출(총이익)

In [70]:
production_data = [
    [100, 150, 120],  # 제품 A의 3일간 생산량
    [200, 180, 220],  # 제품 B의 3일간 생산량
    [90, 110, 100]    # 제품 C의 3일간 생산량
]

In [71]:
prices = np.array([
    [1000, 1100, 1050],  # 제품 A
    [2000, 2100, 2050],  # 제품 B
    [3000, 3100, 3050]   # 제품 C
])

In [72]:
arr1=np.array(production_data)
arr2=prices
print("총매출:", arr1*arr2)

총매출: [[100000 165000 126000]
 [400000 378000 451000]
 [270000 341000 305000]]


In [73]:
production_data = [
    [100, 150, 120],  # 제품 A
    [200, 180, 220],  # 제품 B
    [90, 110, 100]    # 제품 C
]

prices = np.array([
    [1000, 1100, 1050],
    [2000, 2100, 2050],
    [3000, 3100, 3050]
])

# 2. 리스트를 넘파이 배열로 변환
arr1 = np.array(production_data)
arr2 = prices

# 3. 원소별 곱셈 후 전체 합계 구하기
total_sales_per_item = arr1 * arr2
total_revenue = total_sales_per_item.sum()

print("제품별/일별 매출:\n", total_sales_per_item)
print("전체 총매출:", total_revenue)

제품별/일별 매출:
 [[100000 165000 126000]
 [400000 378000 451000]
 [270000 341000 305000]]
전체 총매출: 2536000


In [74]:
profit_per_unit=np.array([20,30,25])

In [75]:
# shape이 같은 배열 간의 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("덧셈:\n", a + b)
print("뺄셈:\n", a - b)
print("곱셈:\n", a * b)
print("나눗셈:\n", a / b)

# shape이 다른 경우 오류 발생
c = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
d = np.array([[1, 2], [3, 4]])        # shape: (2, 2)

# 이 연산은 오류를 발생시킴
# print(c + d)  # ValueError: operands could not be broadcast together

덧셈:
 [[ 6  8]
 [10 12]]
뺄셈:
 [[-4 -4]
 [-4 -4]]
곱셈:
 [[ 5 12]
 [21 32]]
나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [76]:
# 비교 연산 예제
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 3, 0, 5])

# 같음 비교
print("같음:", arr1 == arr2)  # [ True False  True False  True]

# 크기 비교
print("더 큼:", arr1 > arr2)  # [False False False  True False]
print("더 작음:", arr1 < arr2)  # [False  True False False False]

# 논리 연산 결합
mask = (arr1 >= 3) & (arr2 <= 4)
print("복합 조건:", mask)  # [False False  True False False]

# 비교 결과를 이용한 필터링
filtered = arr1[arr1 > 3]
print("3보다 큰 값:", filtered)  # [4 5]

같음: [ True False  True False  True]
더 큼: [False False False  True False]
더 작음: [False  True False False False]
복합 조건: [False False  True  True False]
3보다 큰 값: [4 5]


In [ ]:
# 요소별 연산 예제 Element-wise Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("요소별 덧셈:", a + b)      # [5 7 9]
print("요소별 곱셈:", a * b)      # [4 10 18]
print("요소별 제곱:", np.square(a))  # [1 4 9]
print("요소별 제곱근:", np.sqrt(a))  # [1. 1.41421356 1.73205081]

요소별 덧셈: [5 7 9]
요소별 곱셈: [ 4 10 18]
요소별 제곱: [1 4 9]
요소별 제곱근: [1.         1.41421356 1.73205081]


In [78]:
# 일반 Python 반복문 vs NumPy 벡터화 연산 비교
import numpy as np
import time

# 큰 배열 생성
size = 1000000
arr1 = np.array(range(size))
arr2 = np.array(range(size))
result_list = [0] * size

# Python 반복문 방식
start_time = time.time()
for i in range(size):
    result_list[i] = arr1[i] + arr2[i]
python_time = time.time() - start_time

# NumPy 벡터화 연산 방식
start_time = time.time()
result_numpy = arr1 + arr2
numpy_time = time.time() - start_time

print(f"Python 반복문 실행 시간: {python_time:.4f}초")
print(f"NumPy 벡터화 연산 실행 시간: {numpy_time:.4f}초")
print(f"속도 향상: {python_time/numpy_time:.1f}배")

Python 반복문 실행 시간: 0.2079초
NumPy 벡터화 연산 실행 시간: 0.0011초
속도 향상: 197.1배


In [79]:
# 브로드캐스팅 예제
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
scalar = 2

# 배열과 스칼라의 연산
print("배열 * 스칼라:")
print(arr * scalar)
# [[ 2  4  6]
#  [ 8 10 12]]

# 1차원 배열과 2차원 배열의 연산
row = np.array([1, 0, 1])
print("\n2차원 배열 + 1차원 배열:")
print(arr + row)
# [[2 2 4]
#  [5 5 7]]

배열 * 스칼라:
[[ 2  4  6]
 [ 8 10 12]]

2차원 배열 + 1차원 배열:
[[2 2 4]
 [5 5 7]]


In [81]:
arr2= np.array([0,1,2])
scalar=5
print(arr2*scalar)

[ 0  5 10]


In [82]:
arr3=np.ones((3,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
arr3=np.ones((3,3))
row1=np.array([0,1,2])
print(arr3+row1)


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [88]:
col1 = np.array([0,1,2]).reshape(3,1)  # (3,1)
row1 = np.array([0,1,2]).reshape(1,3)  # (1,3)

result = col1 * row1

print(result)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [89]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # 첫 번째 요소: 1
print(arr[-1])   # 마지막 요소: 5

# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d[0, 1])    # 첫 번째 행, 두 번째 열: 2
print(arr_2d[1, -1])   # 두 번째 행, 마지막 열: 6

1
5
2
6


In [90]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열
# [[2 3]
#  [6 7]]

[2 3 4]
[0 2 4]
[[2 3]
 [6 7]]


In [91]:
# 2차원 배열 예제
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# axis=0 방향 합계 (열 방향 합)
sum_axis0 = np.sum(arr_2d, axis=0)  # [5, 7, 9]

# axis=1 방향 합계 (행 방향 합)
sum_axis1 = np.sum(arr_2d, axis=1)  # [6, 15]

In [94]:
arr_2d1=np.arange(16).reshape(4,4)
arr_2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
arr_2d1[:2,:2] 

array([[0, 1],
       [4, 5]])

In [101]:
base = np.arange(36).reshape(6,6)   # 1층 (6x6)
arr = np.broadcast_to(base, (4,6,6))  # 4층으로 확장

print(arr)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [104]:
arr[0, :3, :3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [105]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열
# [[2 3]
#  [6 7]]

[2 3 4]
[0 2 4]
[[2 3]
 [6 7]]


In [106]:
# 1차원 배열 인덱싱 예제
arr = np.array([10, 20, 30, 40, 50])

# 단일 요소 접근
print("첫 번째 요소:", arr[0])      # 10
print("마지막 요소:", arr[-1])      # 50

# 슬라이싱
print("처음부터 3개:", arr[:3])     # [10 20 30]
print("2번째부터 끝까지:", arr[2:]) # [30 40 50]
print("처음부터 끝까지 2단계씩:", arr[::2]) # [10 30 50]

첫 번째 요소: 10
마지막 요소: 50
처음부터 3개: [10 20 30]
2번째부터 끝까지: [30 40 50]
처음부터 끝까지 2단계씩: [10 30 50]


In [107]:
# 불린 인덱싱 예제
arr = np.array([1, 2, 3, 4, 5])
bool_array = np.array([True, False, True, False, True])
print("불린 인덱싱:", arr[bool_array])  # [1 3 5]

불린 인덱싱: [1 3 5]


In [108]:
# 마스킹 예제
mask = arr > 3  # 조건식으로 마스크 생성
arr[mask] = 0   # 마스크를 사용한 값 수정
print("마스킹 결과:", arr)  # [1 2 3 0 0]

마스킹 결과: [1 2 3 0 0]


In [109]:
# 불리언 인덱싱
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(arr[mask])    # [4 5]

# 팬시 인덱싱
indices = np.array([0, 2, 4])
print(arr[indices])    # [1 3 5]

[4 5]
[1 3 5]
